# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\rando\Desktop\SpringCalicurator\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(606, 695)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.checkBox_no = QtWidgets.QCheckBox(self.groupBox_6)
        self.checkBox_no.setChecked(True)
        self.checkBox_no.setObjectName("checkBox_no")
        self.verticalLayout_5.addWidget(self.checkBox_no)
        self.checkBox_yes = QtWidgets.QCheckBox(self.groupBox_6)
        self.checkBox_yes.setObjectName("checkBox_yes")
        self.verticalLayout_5.addWidget(self.checkBox_yes)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem)
        self.horizontalLayout_2.addWidget(self.groupBox_6)
        self.groupBox_7 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_7.setObjectName("groupBox_7")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_7)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tableView_conditions_steped = QtWidgets.QTableView(self.groupBox_7)
        self.tableView_conditions_steped.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.EditKeyPressed)
        self.tableView_conditions_steped.setObjectName("tableView_conditions_steped")
        self.tableView_conditions_steped.horizontalHeader().setDefaultSectionSize(40)
        self.verticalLayout_2.addWidget(self.tableView_conditions_steped)
        self.horizontalLayout_2.addWidget(self.groupBox_7)
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.tableView_g = QtWidgets.QTableView(self.groupBox_4)
        self.tableView_g.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.EditKeyPressed)
        self.tableView_g.setObjectName("tableView_g")
        self.tableView_g.horizontalHeader().setVisible(False)
        self.tableView_g.horizontalHeader().setDefaultSectionSize(40)
        self.tableView_g.verticalHeader().setVisible(False)
        self.verticalLayout_4.addWidget(self.tableView_g)
        self.horizontalLayout_2.addWidget(self.groupBox_4)
        self.verticalLayout_7.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tableView_force = QtWidgets.QTableView(self.groupBox_3)
        self.tableView_force.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.EditKeyPressed)
        self.tableView_force.setObjectName("tableView_force")
        self.tableView_force.horizontalHeader().setVisible(False)
        self.tableView_force.horizontalHeader().setDefaultSectionSize(40)
        self.tableView_force.verticalHeader().setVisible(False)
        self.verticalLayout_3.addWidget(self.tableView_force)
        self.horizontalLayout_3.addWidget(self.groupBox_3)
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.tableView_d = QtWidgets.QTableView(self.groupBox_5)
        self.tableView_d.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.EditKeyPressed)
        self.tableView_d.setObjectName("tableView_d")
        self.tableView_d.horizontalHeader().setVisible(False)
        self.tableView_d.horizontalHeader().setDefaultSectionSize(40)
        self.tableView_d.verticalHeader().setVisible(False)
        self.verticalLayout_6.addWidget(self.tableView_d)
        self.horizontalLayout_3.addWidget(self.groupBox_5)
        self.verticalLayout_7.addLayout(self.horizontalLayout_3)
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_stop = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_stop.setObjectName("pushButton_stop")
        self.horizontalLayout.addWidget(self.pushButton_stop)
        self.pushButton_start = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_start.setObjectName("pushButton_start")
        self.horizontalLayout.addWidget(self.pushButton_start)
        self.pushButton_count = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_count.setObjectName("pushButton_count")
        self.horizontalLayout.addWidget(self.pushButton_count)
        self.progressBar = QtWidgets.QProgressBar(self.groupBox)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout.addWidget(self.progressBar)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.verticalLayout_7.addWidget(self.groupBox)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.tableView_result = QtWidgets.QTableView(self.tab_2)
        self.tableView_result.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.EditKeyPressed)
        self.tableView_result.setObjectName("tableView_result")
        self.tableView_result.horizontalHeader().setDefaultSectionSize(70)
        self.verticalLayout_8.addWidget(self.tableView_result)
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 606, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SpringCalculator"))
        self.groupBox_6.setTitle(_translate("MainWindow", "研削"))
        self.checkBox_no.setText(_translate("MainWindow", "無し"))
        self.checkBox_yes.setText(_translate("MainWindow", "有り"))
        self.groupBox_7.setTitle(_translate("MainWindow", "寸法[mm]"))
        self.groupBox_4.setTitle(_translate("MainWindow", "横弾性係数[MPa]"))
        self.groupBox_3.setTitle(_translate("MainWindow", "使用時荷重[g]"))
        self.groupBox_5.setTitle(_translate("MainWindow", "線径[mm]"))
        self.groupBox.setTitle(_translate("MainWindow", "処理"))
        self.pushButton_stop.setText(_translate("MainWindow", "停止"))
        self.pushButton_start.setText(_translate("MainWindow", "実行"))
        self.pushButton_count.setText(_translate("MainWindow", "計算数"))
        self.label.setText(_translate("MainWindow", "0/0"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "条件"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "結果"))

